# Generated by Django 4.1.1 on 2022-10-21 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruserdevices',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeruserdevices',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.devices'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customer'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.subscription'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.customertype'),
        ),
    ]
