# Generated by Django 4.1.1 on 2023-06-26 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLicencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_de_plan', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('cobro', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer_user_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical licencia',
                'verbose_name_plural': 'historical licencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_plan', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('cobro', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_user_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='customeruserdevices',
            name='customer_user',
        ),
        migrations.RemoveField(
            model_name='customeruserdevices',
            name='device',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='currencies',
        ),
        migrations.DeleteModel(
            name='Currencies',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerSubscription',
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
        migrations.DeleteModel(
            name='CustomerUserDevices',
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
