# Generated by Django 4.1.1 on 2023-08-08 19:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaccion', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('canal', models.CharField(max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('nombreComprador', models.CharField(max_length=100)),
                ('apellidoComprador', models.CharField(max_length=100)),
                ('documentoComprador', models.CharField(max_length=15)),
                ('modalidad', models.CharField(max_length=100)),
                ('extra1', models.CharField(blank=True, max_length=300)),
                ('extra2', models.CharField(blank=True, max_length=300)),
                ('extra3', models.CharField(blank=True, max_length=300)),
                ('direccionComprador', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=300)),
                ('codigoTransaccion', models.CharField(max_length=300)),
                ('urlRespuesta', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
