# Generated by Django 4.2.6 on 2023-11-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_alter_transaction_documentocomprador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
            ],
        ),
    ]
