# Generated by Django 4.2.6 on 2023-11-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0006_transaction_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='discount',
            new_name='discount_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='description',
        ),
        migrations.AddField(
            model_name='discount',
            name='customer_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('price', 'Price Value'), ('percentage', 'Pecentage Value')], default='percentage', max_length=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='social_media',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='verification_code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
