# Generated by Django 4.2.6 on 2023-11-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_rename_discount_transaction_discount_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pay.productos'),
        ),
    ]
