# Generated by Django 4.2.6 on 2023-11-22 18:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0009_rename_product_discount_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDiscounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('price', 'Price Value'), ('percentage', 'Percentage Value')], default='percentage', max_length=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('emission_date', models.DateField(auto_now_add=True)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.discount')),
                ('id_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_discounts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.productos')),
            ],
        ),
    ]
