# Generated by Django 4.1.1 on 2024-04-19 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0010_saveddiscounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletransaction',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.productos'),
        ),
        migrations.AlterField(
            model_name='saveddiscounts',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saveddiscounts',
            name='id_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsor_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saveddiscounts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.productos'),
        ),
    ]
