# Generated by Django 5.0.3 on 2024-04-22 03:37

from apps.client_contact.models.client_contact import validate_phone_number, validate_comment
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('country_code', models.CharField(max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, validators=[validate_phone_number])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('comment', models.TextField(max_length=280, null=True, validators=[validate_comment])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='¿Desea iniciar contacto? Ingrese sus datos por favor', max_length=254)),
                ('phone_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('comment_enabled', models.BooleanField(default=True)),
                ('customer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer_user',)},
            },
        ),
    ]
