# Generated by Django 5.2.4 on 2025-07-30 20:59

import apps.client_contact.models.client_contact
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(choices=[(0, 'No Leído'), (1, 'Leído')], default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='register',
            name='comment',
            field=models.TextField(blank=True, max_length=280, null=True, validators=[apps.client_contact.models.client_contact.validate_comment]),
        ),
        migrations.AlterField(
            model_name='register',
            name='country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
