# Generated by Django 5.2.4 on 2025-08-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_contact', '0002_register_status_alter_register_comment_and_more'),
        ('client_contact', '0003_alter_register_comment_alter_register_country_code_and_more'),
    ]

    operations = [
    ]
