# Generated by Django 4.1.1 on 2022-11-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusercustomsocialmedia',
            name='image',
            field=models.ImageField(blank='', default='custom_social_media/undefined.png', upload_to='custom_social_media'),
        ),
    ]
