# Generated by Django 4.1.1 on 2022-11-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_customerusercustomsocialmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruseremail',
            name='image',
            field=models.ImageField(blank='', default='contact/icon_correo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='customerusermap',
            name='image',
            field=models.ImageField(blank='', default='contact/icon_ubicacion.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='customeruserphone',
            name='image',
            field=models.ImageField(blank='', default='contact/icon_telefono.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='customeruserwhatsapp',
            name='image',
            field=models.ImageField(blank='', default='contact/icon_whatsapp.png', upload_to=''),
        ),
    ]
