# Generated by Django 4.1.1 on 2023-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_customeruseremail_image_customerusermap_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruserprofile',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.DeleteModel(
            name='CustomerUserDesignProfile',
        ),
    ]
