# Generated by Django 4.1.1 on 2023-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_customeruserprofile_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruserprofile',
            name='background',
            field=models.ImageField(blank='', default='background/image_background.png', upload_to='background'),
        ),
    ]
