# Generated by Django 4.1.1 on 2023-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_customeruserprofile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruserprofile',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
