# Generated by Django 4.1.1 on 2023-06-26 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_customerusercustomsocialmedia_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.customeruserprofile')),
            ],
        ),
    ]
