# Generated by Django 4.1.1 on 2024-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_customerusercustomsocialmedia_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerusercustomsocialmedia',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
