# Generated by Django 4.1.1 on 2023-06-07 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0006_alter_customeruserprofile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusercustomsocialmedia',
            name='type',
            field=models.CharField(blank=True, default='socialMedia', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerUserReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kids', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Nombre', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('custome_user_social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.customerusercustomsocialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUserCustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank='', default='custom_social_media/undefined.png', upload_to='custom_social_media')),
                ('imageQR', models.ImageField(blank='', default='custom_social_media/undefined.png', upload_to='custom_image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
