# Generated by Django 4.1.1 on 2024-01-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_viewprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusercustomsocialmedia',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
