# Generated by Django 5.2.4 on 2025-07-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_alter_customerusercustomsocialmedia_order'),
    ]

    operations = [
    ]
