from .auth import RegisterUser, AuthenticatedView
from .customer_user_viewset import CustomerUserSerializer, CustomerUserViewSet,CustomerAdminViewSet, CustomerUserPutRubroViewSet
from .Register_user import CreateALotOfUsers
from .create_admin_viewset import CreateAdmin
