# Generated by Django 4.1.1 on 2024-01-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='custome_user',
            new_name='customer_user',
        ),
    ]
