# Generated by Django 4.1.1 on 2024-02-01 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_configurationbooking_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationbooking',
            name='btn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='max_reservas',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='max_personas',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
