# Generated by Django 4.1.1 on 2024-02-27 20:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin_noche',
            field=models.TimeField(blank=True, default=datetime.time(19, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_inicio_noche',
            field=models.TimeField(blank=True, default=datetime.time(19, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='max_reservas',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='status_conf',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
