# Generated by Django 5.0.2 on 2024-03-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_configurationbooking_hora_fin_noche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_configuration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.configurationbooking'),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
