# Generated by Django 5.0.6 on 2024-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_booking_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationbooking',
            name='title',
            field=models.CharField(default='Programar Reserva', max_length=30),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='btn',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
