# Generated by Django 5.1.2 on 2024-11-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_configurationbooking_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbooking',
            name='holiday',
            field=models.CharField(blank=True, default='[true,false,false,false,true,true,true]', max_length=100),
        ),
    ]
