from .social_media_viewset import SocialMediaSerializer, SocialmediaViewSet
from .design_profile_viewset import DesignProfileSerializer, DesignProfileViewSet
from .customer_user_custom_social_media_viewset import CustomerUserCustomSocialMediaSerializer, \
    CustomerUserCustomSocialMediaViewSet, CustomerUserCustomSocialMediaByUserViewSet, \
    CustomerUserCustomSocialMediaByAllUserViewSet, customerUserUtilities
from .customer_user_social_media_viewset import CustomerUserSocialMediaSerializer, CustomerUserSocialMediaViewSet
from .customer_user_email_viewset import CustomerUserEmailSerializer, CustomerUserEmailViewSet
from .customer_user_map_viewset import CustomerUserMapSerializer, CustomerUserMapViewSet
from .customer_user_phonenumber_viewset import CustomerUserPhoneSerializer, CustomerUserPhoneViewSet
from .customer_user_whatsapp_viewset import CustomerUserWhatsappSerializer, CustomerUserWhatsappViewSet
from .customer_user_profile_viewset import CustomerUserProfileSerializer, CustomerUserProfileViewSet
from .customer_user_statistics import CustomerUserStatistics, StaticsForAdminViewSet, StaticsForSuperViewSet
from .customer_user_image_viewset import CustomerUserCustomImageSerializer , CustomerUserImageViewSet
from .reserva_viewset import CustomerUserReservaViewSet
from .views_viewset import ViewsViewSet
from .customer_user_without_statics import CustomerUserWithoutStatics
from .customer_user_profile_all_usesrs import CustomerUserAllProfileViewSet, CustomerUserIndepProfileViewSet
from .customer_user_licens_profile_viewset import CustomerUserLicensProfileViewSet
