# Generated by Django 4.1.1 on 2023-06-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_historicallicencia_licencia_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='maternal_surname',
            new_name='rubro',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='paternal_surname',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='licencia_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.licencia'),
        ),
    ]
