# Generated by Django 4.2.6 on 2023-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_maternal_surname_customeruser_rubro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
