# Generated by Django 4.2.6 on 2023-11-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customeruser_is_influencer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_influencer',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='dependency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
