# Generated by Django 4.2.6 on 2023-11-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customeruser_is_influencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
