# Generated by Django 5.0 on 2024-01-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customeruser_is_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_booking',
            field=models.BooleanField(default=False),
        ),
    ]
