# Generated by Django 5.0.3 on 2024-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customeruser_is_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_sales_manager',
            field=models.BooleanField(default=False),
        ),
    ]
