# Generated by Django 4.1.1 on 2024-04-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_licencia_customer_user_admin'),
        ('authentication', '0007_customeruser_is_sales_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='licencia_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.licencia'),
        ),
    ]
