# Generated by Django 4.1.1 on 2024-04-26 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customeruser_licencia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='customer_user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
