# Generated by Django 5.0.6 on 2024-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customeruser_customer_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_ecommerce',
            field=models.BooleanField(default=False),
        ),
    ]
