# Generated by Django 4.1.1 on 2024-01-12 18:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_personas', models.IntegerField(blank=True, default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_bet_booking', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('holiday', models.CharField(blank=True, max_length=100)),
                ('hora_inicio', models.TimeField(default=datetime.time(7, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(18, 0))),
                ('status_conf', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('kids', models.BooleanField(default=False)),
                ('teen', models.BooleanField(default=False)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kids', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('teen', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status_booking', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('code', models.CharField(max_length=10, unique=True)),
                ('custome_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
