# Generated by Django 4.1.1 on 2024-01-30 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_custome_user_booking_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationbooking',
            name='hora_fin_noche',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='hora_fin_tarde',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='hora_inicio_noche',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='configurationbooking',
            name='hora_inicio_tarde',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
