# Generated by Django 4.1.1 on 2024-01-30 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_configurationbooking_hora_fin_noche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin_noche',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin_tarde',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_inicio_noche',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_inicio_tarde',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
    ]
