# Generated by Django 4.1.1 on 2024-01-30 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_configurationbooking_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.time(11, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin_noche',
            field=models.TimeField(blank=True, default=datetime.time(21, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_fin_tarde',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_inicio_noche',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='hora_inicio_tarde',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), null=True),
        ),
    ]
