# Generated by Django 4.1.1 on 2024-02-22 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_configurationbooking_btn_configurationbooking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationbooking',
            name='time_bet_booking',
            field=models.IntegerField(blank=True, default=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
