# Generated by Django 4.1.1 on 2024-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbooking',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
