# Generated by Django 5.0 on 2024-02-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_configurationbooking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
