# Generated by Django 5.0 on 2024-02-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
    ]
