# Generated by Django 5.2.4 on 2025-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20250730_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationbooking',
            name='holiday',
            field=models.CharField(blank=True, default='[true,false,false,false,false,false,true]', max_length=100),
        ),
    ]
