# Generated by Django 4.1.1 on 2023-08-14 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank='', default='productos_images/undefined.png', upload_to='productos_images')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='codigoTransaccion',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_transaccion',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DetalleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantiad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.productos')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.transaction')),
            ],
        ),
    ]
