# Generated by Django 4.1.1 on 2023-08-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_productos_alter_transaction_codigotransaccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalletransaction',
            old_name='cantiad',
            new_name='cantidad',
        ),
    ]
