# Generated by Django 4.1.1 on 2023-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_rename_cantiad_detalletransaction_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='documentoComprador',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extra1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extra2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extra3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
