# Generated by Django 4.2.6 on 2023-11-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_discount_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='product',
            new_name='product_id',
        ),
    ]
