# Generated by Django 5.0.3 on 2024-04-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_saveddiscounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedDiscounts',
        ),
    ]
