# Generated by Django 4.1.1 on 2024-04-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_delete_saveddiscounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletransaction',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.productos'),
        ),
    ]
