# Generated by Django 5.0.6 on 2024-08-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0012_alter_detalletransaction_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Unavailable')], default=2),
        ),
        migrations.AddField(
            model_name='productos',
            name='type',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('furniture', 'Furniture')], default='', max_length=60),
        ),
    ]
