# Generated by Django 5.0.6 on 2024-08-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0013_productos_order_productos_status_productos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(blank=True, default='productos_images/undefined.png', upload_to='productos_images'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='type',
            field=models.CharField(blank=True, choices=[('tarjeta', 'tarjeta'), ('accesorio', 'accesorio')], default='', max_length=60),
        ),
    ]
