# Generated by Django 4.1.1 on 2024-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_alter_productos_image_alter_productos_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='type',
            field=models.CharField(blank=True, choices=[('tarjeta', 'tarjeta'), ('accesorio', 'accesorio')], default='tarjeta', max_length=60),
        ),
    ]
