# Generated by Django 5.2.4 on 2025-07-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_alter_productos_type'),
    ]

    operations = [
    ]
