# Generated by Django 5.0.2 on 2024-04-22 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(choices=[(0, 'No Leído'), (1, 'Leído')], default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
