# Generated by Django 5.0.2 on 2024-04-23 20:35

import client_contact.models.client_contact
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_contact', '0002_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='comment',
            field=models.TextField(blank=True, max_length=280, null=True, validators=[client_contact.models.client_contact.validate_comment]),
        ),
        migrations.AlterField(
            model_name='register',
            name='country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
