from .social_media_viewset import SocialMediaserializers, SocialmediaViewSet
from .design_profile_viewset import DesignProfileserializers, DesignProfileViewSet
from .customer_user_custom_social_media_viewset import CustomerUserCustomSocialMediaserializers, \
    CustomerUserCustomSocialMediaViewSet, \
    CustomerUserCustomSocialMediaByAllUserViewSet, customerUserUtilities
from .customer_user_social_media_viewset import CustomerUserSocialMediaserializers, CustomerUserSocialMediaViewSet
from .customer_user_email_viewset import CustomerUserEmailserializers, CustomerUserEmailViewSet
from .customer_user_map_viewset import CustomerUserMapserializers, CustomerUserMapViewSet
from .customer_user_phonenumber_viewset import CustomerUserPhoneserializers, CustomerUserPhoneViewSet
from .customer_user_whatsapp_viewset import CustomerUserWhatsappserializers, CustomerUserWhatsappViewSet
from .customer_user_profile_viewset import CustomerUserProfileserializers, CustomerUserProfileViewSet, CustomerUserProfileForAdmViewSet
from .customer_user_statistics import CustomerUserStatistics, StaticsForAdminViewSet, StaticsForSuperViewSet
from .customer_user_image_viewset import CustomerUserCustomImageserializers , CustomerUserImageViewSet
from .reserva_viewset import CustomerUserReservaViewSet
from .views_viewset import ViewsViewSet
from .customer_user_without_statics import CustomerUserWithoutStatics
from .customer_user_profile_all_usesrs import CustomerUserAllProfileViewSet
from .customer_user_licens_profile_viewset import CustomerUserLicensProfileViewSet
from .customer_user_custom_order_viewset import customer_user_custom_order_viewset
