# Generated by Django 5.2.4 on 2025-08-08 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
