# Generated by Django 5.0.6 on 2024-05-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_button_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='title',
            new_name='button_title',
        ),
    ]
