# Generated by Django 5.0.6 on 2024-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_title_button_button_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
