# Generated by Django 5.2.4 on 2025-07-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_button_color'),
    ]

    operations = [
    ]
